[package]
name = "atbf-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pom = "3.2.0"
logos = "0.12.1"
ariadne = "0.1.5"
petgraph = "0.6.2"